name: grades_native_test_application
description: "Flutter application that uses FFI for native computations."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '3.22.1'

dependencies:
  cupertino_icons: 1.0.8
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0

dependency_overrides:
  meta: 1.15.0

dev_dependencies:
  build_runner: 2.4.10
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.3
  grades_native_fibonacci: 0.0.1
  json_serializable: 6.8.0

flutter:
  uses-material-design: true
