name: grades_native_test_application
description: "Flutter application that uses FFI for native computations."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: 3.0.0
  grades_native_fibonacci: 0.0.1


flutter:
  uses-material-design: true
